version: '3.8'

services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: minecraft_db
      POSTGRES_USER: mc_user
      POSTGRES_PASSWORD: mc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: